// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testDeleteItem', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testDeleteItem', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1440, height: 875 })
    await driver.findElement(By.linkText("My Trips")).click()
    await driver.findElement(By.linkText("View details")).click()
    await driver.findElement(By.css(".accordion:nth-child(4) .accordion-button")).click()
    await driver.findElement(By.css(".show .single-trip-button")).click()
    {
      const elements = await driver.findElements(By.css(".accordion:nth-child(4) .accordion-button"))
      assert(!elements.length)
    }
  })
})
