// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testAddItem', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testAddItem', async function() {
    await driver.get("http://localhost:3000/Welcome")
    await driver.manage().window().setRect({ width: 1440, height: 875 })
    await driver.findElement(By.linkText("My Trips")).click()
    await driver.findElement(By.linkText("View details")).click()
    await driver.findElement(By.css(".single-trip-button:nth-child(1)")).click()
    await driver.findElement(By.id("formTitle")).click()
    await driver.findElement(By.id("formTitle")).sendKeys("Bike")
    await driver.findElement(By.id("formType")).click()
    {
      const dropdown = await driver.findElement(By.id("formType"))
      await dropdown.findElement(By.xpath("//option[. = 'Activity']")).click()
    }
    await driver.findElement(By.id("formStartTime")).click()
    await driver.findElement(By.id("formStartTime")).sendKeys("12:15")
    await driver.findElement(By.id("formDate")).click()
    await driver.findElement(By.id("formDate")).click()
    await driver.findElement(By.id("formDate")).sendKeys("2023-11-24")
    await driver.findElement(By.id("formEndDate")).click()
    await driver.findElement(By.id("formEndDate")).sendKeys("2023-11-25")
    await driver.findElement(By.id("formDuration")).click()
    {
      const dropdown = await driver.findElement(By.id("formDuration"))
      await dropdown.findElement(By.xpath("//option[. = '2-4 hours']")).click()
    }
    await driver.findElement(By.id("formLocation")).click()
    await driver.findElement(By.id("formLocation")).sendKeys("Van Gogh Museum")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const elements = await driver.findElements(By.css(".accordion:nth-child(5) .accordion-button"))
      assert(elements.length)
    }
  })
})
