// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testMapItems', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testMapItems', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1440, height: 875 })
    await driver.findElement(By.linkText("My Trips")).click()
    {
      const element = await driver.findElement(By.linkText("My Trips"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".d-flex:nth-child(2) .col:nth-child(2) .card-details")).click()
    await driver.findElement(By.css(".single-trip-button:nth-child(1)")).click()
    await driver.findElement(By.id("formTitle")).click()
    await driver.findElement(By.id("formTitle")).sendKeys("Duomo")
    await driver.findElement(By.id("formType")).click()
    {
      const dropdown = await driver.findElement(By.id("formType"))
      await dropdown.findElement(By.xpath("//option[. = 'Activity']")).click()
    }
    await driver.findElement(By.id("formStartTime")).click()
    await driver.findElement(By.id("formStartTime")).sendKeys("12:15")
    await driver.findElement(By.id("formDate")).click()
    await driver.findElement(By.id("formDate")).sendKeys("2023-11-24")
    await driver.findElement(By.id("formEndDate")).click()
    await driver.findElement(By.id("formEndDate")).click()
    await driver.findElement(By.id("formEndDate")).sendKeys("2023-11-24")
    await driver.findElement(By.id("formDuration")).click()
    {
      const dropdown = await driver.findElement(By.id("formDuration"))
      await dropdown.findElement(By.xpath("//option[. = '2-4 hours']")).click()
    }
    await driver.findElement(By.id("formLocation")).click()
    await driver.findElement(By.id("formLocation")).sendKeys("Cattedrale Santa Maria")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    assert(await driver.findElement(By.css(".accordion:nth-child(4) .accordion-button")).getText() == "Duomo")
  })
})
